<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>_001_VMT.Application</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\001-VMT.Persistence\001-VMT.Persistence.csproj" />
    <ProjectReference Include="..\..\Shared\001-VMT.Shared\001-VMT.Shared.csproj" />
    <ProjectReference Include="..\001-VMT.Domain\001-VMT.Domain.csproj" />
  </ItemGroup>

</Project>